export const staticApi = {
    uz: {
        navbar: ["Asosiy", "Haqida", "Xizmatlar", "Portfolio", "Yutuqlar"],
        navbarDrop: ["Mijozlar", "Bizning jamoamiz", "Izohlar"],
        heroBtns: ["Bog'lanish", "Buyurtma berish"],
        titleXizmatlar: "Xizmatlar",
        titleAbout: "Biz haqimizda",
        titleYutuqlar: "Yutuqlarimiz",
        titlePortfolio: "Portfolio",
        titleClient: "Mijozlar",
        titleJamoa: "Bizning jamoamiz",
        titleGuvoh: "Izohlar",
        solveProblem: "Muammoingizni hal qilish uchun bizga qo'ng'iroq qiling",
        formNumberLabel: "Telefon raqam",
        formNumberInput: "Telefon raqamingizni kiriting",
        formNameLabel: "Ism",
        formNameInput: "Ismingizni kiriting",
        formBtnSubmit: "Tasdiqlash",
    },
    ru: {
        navbar: ["Основной", "О", "Услуги", "Портфолио", "Достижения"],
        navbarDrop: ["Клиенты", "Наша команда", "Свидетели"],
        heroBtns: ["Связь", "Разместить заказ"],
        titleXizmatlar: "Услуги",
        titleAbout: "О нас",
        titleYutuqlar: "Наши достижения",
        titlePortfolio: "Портфолио",
        titleClient: "Клиенты",
        titleJamoa: "Наша команда",
        titleGuvoh: "Свидетели",
        solveProblem: "Позвоните нам, чтобы решить вашу проблему",
        formNumberLabel: "Номер телефона",
        formNumberInput: "Введите свой номер телефона",
        formNameLabel: "Имя",
        formNameInput: "Введите ваше имя",
        formBtnSubmit: "Подтверждение",
    },
    en: {
        navbar: ["Home", "About", "Service", "Portfolio", "Achievements"],
        navbarDrop: ["Clients", "Our team", "Testimonials"],
        heroBtns: ["Call", "Place an order"],
        titleXizmatlar: "Services",
        titleAbout: "About Us",
        titleYutuqlar: "Achievements",
        titlePortfolio: "Portfolio",
        titleClient: "Clients",
        titleJamoa: "Our team",
        titleGuvoh: "Testimonials",
        solveProblem: "Call us to solve your problem",
        formNumberLabel: "Phone number",
        formNumberInput: "Enter your phone number",
        formNameLabel: "Name",
        formNameInput: "Enter your name",
        formBtnSubmit: "Confirm",
    },
};
